[server]
port=1234

[psql]
ssl_mode="disable"
database="exercise_parser"
user="exercise"
password="parser"
host="localhost"
port=5432
logging=false

[migration]
dir="migrations"

[s3]
enabled="true"
region="us-east-2"
