[server]
port=1234

[psql]
ssl_mode="disable"
database="streaming"
user="server"
password="server"
host="localhost"
port=5432
logging=false

[migration]
dir="migrations"

[s3]
enabled="true"
region="us-east-2"
